### ISSUE TITLE
Fix failing segmentation workflows

### ISSUE THREAD

**Issue by yrkim98** [AllenCell/napari-allencell-segmenter#163]
Currently segmentation workflows are failing with this error
```
AttributeError                            Traceback (most recent call last)
File ~/anaconda3/envs/ml-seg/lib/python3.10/site-packages/superqt/utils/_qthreading.py:617, in create_worker.<locals>.reraise(e=AttributeError("module 'itk' has no attribute 'GetImageFromArray'"))
    616 def reraise(e):
--> 617     raise e
        e = AttributeError("module 'itk' has no attribute 'GetImageFromArray'")
```

Need to make this fix on `aics-segmentation`

**Comment by yrkim98** [comment]
tried pinning to `itk==5.2.1` but that version was not available on pypi.
tried pinning to `itk==5.0.1` but that version fails with build errors
```
Building wheels for collected packages: itk
  Building wheel for itk (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for itk
  Running setup.py clean for itk
Failed to build itk
```
